@host = http://localhost:5116

### Auth Section

POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "superAdmin@devvault.com",
    "password": "SuperAdmin123!"
}

### User Manager Section

POST {{host}}/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiN2RmZTFjZWEtZjA4Zi00MjQwLThiYmQtMmZiOGZjMjNiODI0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MzQyNDE3NywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.4MweGeL3dcC9HIYLE87Sr4NBzyZ1_YEipHZhrMrWAxo
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "John123!",
    "firstName": "John",
    "lastName": "Doe",
    "roleId": "51050ed4-c7fa-420c-ae5a-af2389d41e57"
}

###

POST {{host}}/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNGMxMDBhNDQtOTdmZC00NGViLWEzNGUtZWYwNjVlNzA2YjY0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MjA0Nzc4NiwiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.-2qZtM693m_FOlz-0LwPqIweFFi7KmFzh_3hWrHvS0o
Content-Type: application/json

{
    "email": "mike@example.com",
    "password": "Mike123!",
    "firstName": "Mike",
    "lastName": "Loe",
    "roleId": "91d10df9-ff40-4658-8530-22fd7d75c413"
}

###

GET {{host}}/api/v1/users?pageNumber=1&pageSize=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNjAwNmQwNWEtNDZiMy00YmQ4LWFjYTItMDY1MmQ2M2E5Nzk3IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4NDcyMzA3MywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.Y3A2hUa0sTsVALd5gvhWLGVkBSxjG6OoPUk1i7DoHt8
Content-Type: application/json

### Project Manager Section

POST {{host}}/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNGMxMDBhNDQtOTdmZC00NGViLWEzNGUtZWYwNjVlNzA2YjY0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MjA0Nzc4NiwiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.-2qZtM693m_FOlz-0LwPqIweFFi7KmFzh_3hWrHvS0o
Content-Type: application/json

{
  "name": "Personal Password Manager",
  "description": "A secure vault for storing and managing personal account credentials and sensitive information."
}

###

POST {{host}}/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNGMxMDBhNDQtOTdmZC00NGViLWEzNGUtZWYwNjVlNzA2YjY0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MjA0Nzc4NiwiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.-2qZtM693m_FOlz-0LwPqIweFFi7KmFzh_3hWrHvS0o
Content-Type: application/json

{
  "name": "TODO List Ap",
  "description": "A Flexible tool for managing work."
}

###

GET {{host}}/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiN2RmZTFjZWEtZjA4Zi00MjQwLThiYmQtMmZiOGZjMjNiODI0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MzQyNDE3NywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.4MweGeL3dcC9HIYLE87Sr4NBzyZ1_YEipHZhrMrWAxo
Content-Type: application/json

###

GET {{host}}/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNGMxMDBhNDQtOTdmZC00NGViLWEzNGUtZWYwNjVlNzA2YjY0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MjA0Nzc4NiwiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.-2qZtM693m_FOlz-0LwPqIweFFi7KmFzh_3hWrHvS0o
Content-Type: application/json


###

DELETE  {{host}}/api/v1/projects/85775983-b0b6-48eb-bc63-368c32d9fd3a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNGMxMDBhNDQtOTdmZC00NGViLWEzNGUtZWYwNjVlNzA2YjY0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MjA0Nzc4NiwiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.-2qZtM693m_FOlz-0LwPqIweFFi7KmFzh_3hWrHvS0o
Content-Type: application/json

###

PUT  {{host}}/api/v1/projects/e209d8d8-9309-44c4-b8a8-55ea5dc92a38
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNGMxMDBhNDQtOTdmZC00NGViLWEzNGUtZWYwNjVlNzA2YjY0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MjA0Nzc4NiwiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.-2qZtM693m_FOlz-0LwPqIweFFi7KmFzh_3hWrHvS0o
Content-Type: application/json

{
  "name": "TODO APP",
  "description": "A Flexible tool for managing work."
}

###

POST {{host}}/api/v1/projects/e209d8d8-9309-44c4-b8a8-55ea5dc92a38/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiN2RmZTFjZWEtZjA4Zi00MjQwLThiYmQtMmZiOGZjMjNiODI0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MzQyNDE3NywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.4MweGeL3dcC9HIYLE87Sr4NBzyZ1_YEipHZhrMrWAxo
Content-Type: application/json

{
  "email": "mike@example.com",
  "role": "Viewer"
}

###

GET {{host}}/api/v1/projects/e209d8d8-9309-44c4-b8a8-55ea5dc92a38/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiN2RmZTFjZWEtZjA4Zi00MjQwLThiYmQtMmZiOGZjMjNiODI0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MzQyNDE3NywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.4MweGeL3dcC9HIYLE87Sr4NBzyZ1_YEipHZhrMrWAxo
Content-Type: application/json

### Secrets Manager
POST {{host}}/api/v1/projects/e209d8d8-9309-44c4-b8a8-55ea5dc92a38/secrets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiNjAwNmQwNWEtNDZiMy00YmQ4LWFjYTItMDY1MmQ2M2E5Nzk3IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4NDcyMzA3MywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.Y3A2hUa0sTsVALd5gvhWLGVkBSxjG6OoPUk1i7DoHt8
Content-Type: application/json

{
  "projectId": "e209d8d8-9309-44c4-b8a8-55ea5dc92a38",
  "key": "MasterKey",
  "value": "yN7+d3vR9/aL4xQ8bE2jW5mP1uC6sK0zV4nF9hT3bA8="
}

###

GET {{host}}/api/v1/projects/e209d8d8-9309-44c4-b8a8-55ea5dc92a38/secrets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiN2RmZTFjZWEtZjA4Zi00MjQwLThiYmQtMmZiOGZjMjNiODI0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MzQyNDE3NywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.4MweGeL3dcC9HIYLE87Sr4NBzyZ1_YEipHZhrMrWAxo
Content-Type: application/json

### 

GET {{host}}/api/v1/projects/e209d8d8-9309-44c4-b8a8-55ea5dc92a38/secrets/ade08efd-cab0-43b4-be65-0c825c1af995/reveal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiN2RmZTFjZWEtZjA4Zi00MjQwLThiYmQtMmZiOGZjMjNiODI0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MzQyNDE3NywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.4MweGeL3dcC9HIYLE87Sr4NBzyZ1_YEipHZhrMrWAxo
Content-Type: application/json

### Audit Logs Section
GET {{host}}/api/v1/audit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTY5ZDg1MC1jMWVhLTQ5ZWItODBhMi03NmRkZDBiODc0OWQiLCJlbWFpbCI6InN1cGVyQWRtaW5AZGV2dmF1bHQuY29tIiwianRpIjoiN2RmZTFjZWEtZjA4Zi00MjQwLThiYmQtMmZiOGZjMjNiODI0IiwiZmlyc3ROYW1lIjoiU3lzdGVtIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4MzQyNDE3NywiaXNzIjoiRGV2VmF1bHRBUEkiLCJhdWQiOiJEZXZWYXVsdFVzZXJzIn0.4MweGeL3dcC9HIYLE87Sr4NBzyZ1_YEipHZhrMrWAxo
Content-Type: application/json
